services:
  service-registry:
    image: ${DOCKER_USERNAME}/service-registry:latest
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      - ZIPKIN_CONNECTION_URL=${ZIPKIN_CONNECTION_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  config-server:
    image: ${DOCKER_USERNAME}/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      service-registry:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - ZIPKIN_CONNECTION_URL=${ZIPKIN_CONNECTION_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # DATABASES
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "password", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # OBSERVABILITY TOOLS
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9411/zipkin/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # MESSAGE BROKER
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

      KAFKA_LISTENERS: 'INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list" ]
      interval: 15s
      timeout: 10s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: 'Local Kafka Cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:29092'

  # MICROSERVICES
  api-gateway:
    image: ${DOCKER_USERNAME}/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_SERVER_CONNECTION=${SPRING_CONFIG_SERVER_CONNECTION}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - ZIPKIN_CONNECTION_URL=${ZIPKIN_CONNECTION_URL}
      - KAFKA_CONNECTION=${KAFKA_CONNECTION}

  auth-service:
    image: ${DOCKER_USERNAME}/auth-service:latest
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_SERVER_CONNECTION=${SPRING_CONFIG_SERVER_CONNECTION}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - ZIPKIN_CONNECTION_URL=${ZIPKIN_CONNECTION_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - KAFKA_CONNECTION=${KAFKA_CONNECTION}

  citizen-service:
    image: ${DOCKER_USERNAME}/citizen-service:latest
    container_name: citizen-service
    ports:
      - "8082:8082"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_SERVER_CONNECTION=${SPRING_CONFIG_SERVER_CONNECTION}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - ZIPKIN_CONNECTION_URL=${ZIPKIN_CONNECTION_URL}
      - KAFKA_CONNECTION=${KAFKA_CONNECTION}

  complaint-service:
    image: ${DOCKER_USERNAME}/complaint-service:latest
    container_name: complaint-service
    ports:
      - "8083:8083"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
      kafka:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_SERVER_CONNECTION=${SPRING_CONFIG_SERVER_CONNECTION}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - ZIPKIN_CONNECTION_URL=${ZIPKIN_CONNECTION_URL}
      - KAFKA_CONNECTION=${KAFKA_CONNECTION}

  department-admin-service:
    image: ${DOCKER_USERNAME}/department-admin-service:latest
    container_name: department-admin-service
    ports:
      - "8084:8084"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
      kafka:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_SERVER_CONNECTION=${SPRING_CONFIG_SERVER_CONNECTION}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - ZIPKIN_CONNECTION_URL=${ZIPKIN_CONNECTION_URL}
      - KAFKA_CONNECTION=${KAFKA_CONNECTION}

  department-staff-service:
    image: ${DOCKER_USERNAME}/department-staff-service:latest
    container_name: department-staff-service
    ports:
      - "8085:8085"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
      kafka:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_SERVER_CONNECTION=${SPRING_CONFIG_SERVER_CONNECTION}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - ZIPKIN_CONNECTION_URL=${ZIPKIN_CONNECTION_URL}
      - KAFKA_CONNECTION=${KAFKA_CONNECTION}

  issue-service:
    image: ${DOCKER_USERNAME}/issue-service:latest
    container_name: issue-service
    ports:
      - "8086:8086"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
      kafka:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_SERVER_CONNECTION=${SPRING_CONFIG_SERVER_CONNECTION}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - ZIPKIN_CONNECTION_URL=${ZIPKIN_CONNECTION_URL}
      - KAFKA_CONNECTION=${KAFKA_CONNECTION}

volumes:
  mongo-data:
  redis-data: