spring:
  application:
    name: citizen-service
  config:
    import: optional:configserver:${SPRING_CONFIG_SERVER_CONNECTION}
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@