name: Build and Deploy Auth Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'auth-service/**'
      - 'pom.xml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

# --- ADD THIS TEMPORARY DEBUGGING STEP ---
          # --- ADD THIS NEW, MORE ROBUST DEBUGGING STEP ---
      - name: ▀▄▀▄▀▄ DEBUG - Inspect Secret Content (v2) ▄▀▄▀▄▀
        run: |
          echo "--- Start of Base64 Secret ---"
          base64 <<< "${{ secrets.MAVEN_SETTINGS_XML }}"
          echo "--- End of Base64 Secret ---"
          exit 1
          # ---------------------------------------------------

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create Maven settings.xml from secret
        uses: BoundfoxStudios/action-write-file@v1
        with:
          # The path to the file you want to create in the workspace.
          path: ./settings.xml
          # The content to write to the file, taken directly from your secret.
          contents: ${{ secrets.MAVEN_SETTINGS_XML }}
          # This ensures the action can handle multi-line content.
          write-mode: overwrite

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./auth-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest 
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:0.0.1-SNAPSHOT
          build-args: |
            MODULE_DIR=auth-service
          secrets: |
            maven-settings=settings.xml
          cache-from: type=gha
          cache-to: type=gha,mode=max
