name: Build and Deploy Auth Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'auth-service/**'
      - 'pom.xml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Maven Settings
        run: |
          # Decode and save to file in the repo root (build context)
          echo "${{ secrets.MAVEN_SETTINGS_BASE64 }}" | base64 -d > settings.xml
          # Verify it's valid XML
          echo "First line of settings.xml:"
          head -1 settings.xml
          echo "Full path:"
          pwd
          ls -la settings.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./auth-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest 
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:0.0.1-SNAPSHOT
          build-args: |
            MODULE_DIR=auth-service
          secrets: |
            maven-settings=./settings.xml
          cache-from: type=gha
          cache-to: type=gha,mode=max
