name: Build and Deploy Issue Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'issue-service/**'
      - 'pom.xml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image to Docker Hub
        env:
          IMAGE_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/issue-service:0.0.1-SNAPSHOT"
        run: |
          docker build -t $IMAGE_TAG -f issue-service/Dockerfile issue-service
          docker push $IMAGE_TAG
